version: '3.9'

services:
  app:
    volumes:
      - type: bind
        source: /etc/{{ short_name }}/config.json
        target: /etc/{{ short_name }}/config.json
        read_only: true
    ports:
      - 127.0.0.1:{{ ports.prod.app }}:8000/tcp
{% if 'app_second' in ports.prod %}      - 127.0.0.1:{{ ports.prod.app_second }}:8001/tcp{% endif %}
  db:
    volumes:
      - type: bind
        source: /etc/{{ short_name }}/config.json
        target: /etc/{{ short_name }}/config.json
        read_only: true
    ports:
      - 127.0.0.1:{{ ports.prod.db }}:5432/tcp
